### ISSUE TITLE
Lista de temas ignorados lleva a portada del foro si no hay ninguno

### ISSUE THREAD

**Issue by dtraid** [mediavida/mediavida7#12]
- **¿Cúal es el problema?**

La [lista de temas ignorados](http://beta.mediavida.com/foro/ignorados) lleva a la portada del foro cuando no hay ninguno.

- **Pasos para reproducirlo:**

Ir a la [lista de temas ignorados](http://beta.mediavida.com/foro/ignorados) con un usuario que no tenga ningún tema ignorado.

- **¿Cuál debería ser el funcionamiento correcto?**

Mostrar la página de ignorados con un texto indicando que no hay ninguno: "No tienes ningún tema ignorado."

- **Más información:**
    - Sistema operativo / Dispositivo móvil:
    - Versión de navegador:

**Comment by beavis** [comment]
solucionado problema con rutas de nginx
