### ISSUE TITLE
Spy Top Semanal no funciona

### ISSUE THREAD

**Issue by mvdog** [mediavida/mediavida7#17]
**¿Cúal es el problema?**
 Spy -&gt; Top -&gt; Semanal muestra el top de hoy
 **Pasos para reproducirlo:**
 Voy a Spy -&gt; Top, y pulso Semanal, la página parece recargarse, pero sigue mostrando el Top de hoy, tanto en el titulo cómo en los Post que se muestran
 
 **¿Cuál debería ser el funcionamiento correcto?**
 
 Debería mostrar el top semanal en vez de el top de hoy
 
 **Más información:**
 - Sistema operativo / Dispositivo móvil: MacOS Sierra 10.12.3
 - Versión de navegador: Safari 10.0.3 y Google Chrome Version 56.0.2924.87 (64-bit)
 - Capturas de pantalla (si es un bug visual) 
 
  Reportado en http://www.mediavida.com/foro/tema.php?fid=4&tid=581711#2

**Comment by dtraid** [comment]
Mensual tampoco funciona.
