### ISSUE TITLE
Imagen de perfil no editable

### ISSUE THREAD

**Issue by mvdog** [mediavida/mediavida7#18]
**¿Cúal es el problema?**
 cuando pones una nueva imagen de perfil, los botones de acercar y alejar imagen no funcionan.
 
 **Pasos para reproducirlo:**
 subir imagen, pulsar botones observar como no funcionan
 
 **¿Cuál debería ser el funcionamiento correcto?**
 poder dejar el perfil chachi alejando y acercando la imagen a gusto del usuario
 
 **Más información:**
 - Sistema operativo / Dispositivo móvil: w7
 - Versión de navegador: firefox 52.0.2
 
 
  Reportado en http://www.mediavida.com/foro/tema.php?fid=4&tid=581711#5

**Comment by dtraid** [comment]
A mí sí que me funciona en Firefox OS X.

**Comment by dtraid** [comment]
Crashea en Firefox Android.
