### ISSUE TITLE
No funciona el desplegable de cambiar tema en móvil

### ISSUE THREAD

**Issue by mvdog** [mediavida/mediavida7#22]
**¿Cúal es el problema?**
 Cuando quieres cambiar entre los themes en tu perfil no funciona, no se despliega la lista 
 **Pasos para reproducirlo:**
 Vas a tu perfil, click en cambiar color de fondo y no hace nada
 **¿Cuál debería ser el funcionamiento correcto?**
 En mi caso, click encima del color &#039;blanco&#039; y debería salir una lista con el negro y asi poder cambiar
 **Más información:**
 - Sistema operativo / Dispositivo móvil: Android y Chrome
 
 
 
  Reportado en http://www.mediavida.com/foro/tema.php?fid=4&tid=581711#10

**Comment by beavis** [comment]
no soy capaz de reproducirlo
