### ISSUE TITLE
Error 404 en links a eventos

### ISSUE THREAD

**Issue by mvdog** [mediavida/mediavida7#26]
**¿Cúal es el problema?**
 Los enlaces en el sidebar que apuntan a los eventos, tienen una doble slash en la url que hace que en destino de 404.
 
 **Pasos para reproducirlo:**
 Ver listado de eventos en la portada de un foro. Por ejemplo, en Deportes
 
 **¿Cuál debería ser el funcionamiento correcto?**
 Url válida
 
 **Más información:**
 - Sistema operativo / Dispositivo móvil: Win 7 / desktop
 - Versión de navegador: Chrome 56.0
 - Capturas de pantalla (si es un bug visual)
 
  Reportado en http://www.mediavida.com/foro/tema.php?fid=4&tid=581711#15

**Comment by dtraid** [comment]
El problema es que no añade el nombre del foro a la URL.

Ej: http://www.mediavida.com/foro//la-liga-jornada-29-580838
