### ISSUE TITLE
Boton Responder no funciona

### ISSUE THREAD

**Issue by mvdog** [mediavida/mediavida7#29]
**¿Cúal es el problema?**
 Si le doy al botón &quot;Responder&quot; como en las versiones anteriores, hay veces que no sale nada
 **Pasos para reproducirlo:**
 Como bien se indica en el cajetín, se postea mediante &quot;CTRL+INTRO&quot;
 **¿Cuál debería ser el funcionamiento correcto?**
 No sé si es por que deberia ser asi o no pero resulta bastante incomodo, al menos a mi me resulta mas comodo clicar&amp;mandar
 **Más información:**
 - Sistema operativo / Dispositivo móvil: Windows 10 Pro
 - Versión de navegador:Versión 57.0.2987.133 (64-bit)
 - Capturas de pantalla (si es un bug visual)
 
  Reportado en http://www.mediavida.com/foro/tema.php?fid=4&tid=581711#20

**Comment by dtraid** [comment]
Aquí creo que el problema es lo que ya hablamos de que los dos botones de responder tienen acciones distintas. Seguramente le esté dando al de arriba.
