### ISSUE TITLE
Cambiar el tema de la web desde el móvil

### ISSUE THREAD

**Issue by mvdog** [mediavida/mediavida7#30]
**¿Cúal es el problema?**
 No funciona el desplegable para cambiar el tema (claro/oscuro) desde el móvil. 
 
 **Pasos para reproducirlo:**
 Entrar a configuración y pulsar en el desplegable. 
 
 **¿Cuál debería ser el funcionamiento correcto?**
 Que el desplegable se despliegue (xD) 
 
 **Más información:**
 - Sistema operativo / Dispositivo móvil: LG G3, Android 6.0
 - Versión de navegador: Chrome 
 - Capturas de pantalla (si es un bug visual)
 
  Reportado en http://www.mediavida.com/foro/tema.php?fid=4&tid=581711#21

**Comment by dtraid** [comment]
Duplicada de #30.

**Comment by dtraid** [comment]
Duplicada de #22.
