### ISSUE TITLE
No puedo finalizar el registro de un nuevo usuario

### ISSUE THREAD

**Issue by mvdog** [mediavida/mediavida7#32]
**¿Cúal es el problema?**
 Recibo el mail para la activación de la cuenta, pero al pulsarlo recibo el error
 &quot;Esta página no funciona
 La página www.mediavida.com te ha redirigido demasiadas veces.
 Borrar las cookies.
 ERR_TOO_MANY_REDIRECTS&quot;
 
 Y no puedo logear con el nuevo usuario. He probado desde distintos ordenadores desde redes distintas.
 
 **Pasos para reproducirlo:**
 
 **¿Cuál debería ser el funcionamiento correcto?**
 
 **Más información:**
 - Sistema operativo / Dispositivo móvil: Ubuntu 16.10 / Windows 10
 - Versión de navegador: Chromium
 - Capturas de pantalla (si es un bug visual)
 
  Reportado en http://www.mediavida.com/foro/tema.php?fid=4&tid=581711#29

**Comment by dtraid** [comment]
Comprobado en Chrome macOS.
