### ISSUE TITLE
No funciona la cruz de eliminar posts no leídos en el listado de temas del perfil

### ISSUE THREAD

**Issue by dtraid** [mediavida/mediavida7#33]
- **¿Cúal es el problema?**

No funciona la cruz de eliminar posts no leídos en el listado de temas del perfil

- **Pasos para reproducirlo:**

Ir a tu perfil teniendo algun hilo de los últimos en los que has posteado en el que queden comentarios sin leer, y darle a la cruz a la derecha del número.

- **¿Cuál debería ser el funcionamiento correcto?**

Debería eliminar los posts no leídos, o no debería aparecer.

- **Más información:**
    - Sistema operativo / Dispositivo móvil: macOS
    - Versión de navegador: Chrome

**Comment by beavis** [comment]
fixed
