### ISSUE TITLE
El selector de categoria al crear un hilo nuevo no funciona en Android

### ISSUE THREAD

**Issue by mvdog** [mediavida/mediavida7#35]
**¿Cúal es el problema?**
 El input select de introducir categoría cuando le das a nuevo post, no funciona
 **Pasos para reproducirlo:**
 Nuevo post-&gt; seleccionar categoría
 **¿Cuál debería ser el funcionamiento correcto?**
 Debería dejar elegir una categoría
 **Más información:**
 - Sistema operativo / Dispositivo móvil:
 Android 7.1 en OnePlus One con LineageOS
 - Versión de navegador: la ultima de chrome
 
  Reportado en http://www.mediavida.com/foro/tema.php?fid=4&tid=581711&pagina=2#34

**Comment by dtraid** [comment]
Parece que tiene que ver con que el textbox del título cambia de tamaño:

![cqsidbs](https://cloud.githubusercontent.com/assets/1199105/24619571/b2e2464c-189a-11e7-9884-8881d9754928.png)
