### ISSUE TITLE
Nombre de perfil fuera de sitio

### ISSUE THREAD

**Issue by mvdog** [mediavida/mediavida7#40]
**¿Cúal es el problema?**
 El nombre de mi perfil se mete entre los botones bajando de su posición original.
 
 **Pasos para reproducirlo:**
 Me pasa siempre, sin hacer nada especifico. Primero se coloca en su sitio pero poco después se desplaza hacia abajo.
 
 **¿Cuál debería ser el funcionamiento correcto?**
 
 **Más información:**
 - Sistema operativo / Dispositivo móvil: Windows 10
 - Versión de navegador: Chrome
 - Capturas de pantalla (si es un bug visual) [img]https://gyazo.com/6fd9fc6e301ad0294fcd7f79019189ff[/img]
 
  Reportado en http://www.mediavida.com/foro/tema.php?fid=4&tid=581711&pagina=2#46

**Comment by dtraid** [comment]
Es una extensión.
