### ISSUE TITLE
Excesiva separación entre el textare de respuesta rápido y el botón de enviar

### ISSUE THREAD

**Issue by mvdog** [mediavida/mediavida7#45]
**¿Cúal es el problema?**
 Encuentro que hay mucha separación entre el textarea de respuesta rápida y el botón de enviar.
 
 **Pasos para reproducirlo:**
 Abrir el formulario de respuesta rápida
 
 **¿Cuál debería ser el funcionamiento correcto?**
 Que el espacio entre estos dos componentes sea mínimo
 
 **Más información:**
 - Sistema operativo / Dispositivo móvil: Ubuntu 16.04
 - Versión de navegador: Firefox 52.0.2
 - Capturas de pantalla (si es un bug visual)
 
 
  Reportado en http://www.mediavida.com/foro/tema.php?fid=4&tid=581711&pagina=2#56

**Comment by dtraid** [comment]
Duplicado de #24.
