### ISSUE TITLE
EEl avatar no sale en su sitio

### ISSUE THREAD

**Issue by mvdog** [mediavida/mediavida7#46]
**¿Cúal es el problema?**
 
 **Pasos para reproducirlo:**
 Entrar en MV
 **¿Cuál debería ser el funcionamiento correcto?**
 Pues arriba en la barra con todo.
 **Más información:**
 - Sistema operativo / Dispositivo móvil: W10
 - Versión de navegador: Firefox 52.0.2
 - Capturas de pantalla (si es un bug visual): 
 [img]https://i.gyazo.com/f8535e46695431d32834869824f44ab4.png[/img]
 
  Reportado en http://www.mediavida.com/foro/tema.php?fid=4&tid=581711&pagina=2#59

**Comment by dtraid** [comment]
Extensión.
