### ISSUE TITLE
Falta el boton FILTRAR en el apartado de hilos TOP

### ISSUE THREAD

**Issue by mvdog** [mediavida/mediavida7#48]
**¿Cúal es el problema?**
 Cuando entras en Spy, Nuevos, Top, Noticias, todos tiene botón de filtrar foros salvo el apartado TOP.
 **Pasos para reproducirlo:**
 Clic en Spy, y pasar al apartado Top
 **¿Cuál debería ser el funcionamiento correcto?**
 Entiendo que los filtros de foros también deberian funcionar cuando hace el Top de hilos.
 **Más información:**
 - Sistema operativo / Dispositivo móvil: Win10
 - Versión de navegador: Chrome Versión 56.0.2924.87
 - Capturas de pantalla (si es un bug visual)
 [img]http://i.imgur.com/uSiPdIl.png[/img]
 
 [img]http://i.imgur.com/MW9Uxey.png[/img]
 
  Reportado en http://www.mediavida.com/foro/tema.php?fid=4&tid=581711&pagina=3#76

**Comment by beavis** [comment]
esto no es un bug
