### ISSUE TITLE
Escribe aquí el resumen del bug en una frase

### ISSUE THREAD

**Issue by mvdog** [mediavida/mediavida7#71]
**¿Cúal es el problema?**
 
 Después de hacer blacklisted a un usuario tengo a todo MV blacklisted
 
 **Pasos para reproducirlo:**
 
 Me ha ocurrido dandole a blacklist a un usuario en un hilo Live!
 
 **¿Cuál debería ser el funcionamiento correcto?**
 
 Haber afectado solo a ese usuario, no a toda MV
 
 **Más información:**
 - Sistema operativo / Dispositivo móvil: OS X El Capitan, Version 10.11.6
 - Versión de navegador: Chrome, Version 58.0.3029.110 (64-bit)
 - Capturas de pantalla (si es un bug visual)
 
  Reportado en http://www.mediavida.com/foro/tema.php?fid=4&tid=581711&pagina=6#155

**Comment by dtraid** [comment]
Es del MV Usertools
